apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: insurance-service
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:tenex-ai/app.git
    targetRevision: master
    path: helm-charts/helm-chart-api
    helm:
      valueFiles:
        - values-insurance-service.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
