global:
  domain: ""

configs:
  cm:
    statusbadge.enabled: 'true'
    application.namespaces: "*"
  params:
    server.insecure: 'true'
  rbac:
    create: 'true'
    policy.default: 'role:admin'
    policy.csv: |
      p, role:admin, applications, *, */*, allow
      p, role:admin, clusters, *, *, allow
      p, role:admin, repositories, *, *, allow
      p, role:admin, projects, *, *, allow
      p, role:admin, logs, *, *, allow
      p, role:admin, exec, *, */*, allow

  repositories:
    tenex-ai-app:
      name: tenex-ai-app
      type: git
      url: git@github.com:tenex-ai/app.git

  credentialTemplates: {}

server:
  ingress:
    enabled: true
    controller: generic
    annotations:
      alb.ingress.kubernetes.io/group.name: dev-apex-dev-internet-facing
      alb.ingress.kubernetes.io/healthcheck-path: /healthz
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
    ingressClassName: "alb"
    hostname: ""
    path: /
    pathType: Prefix
