{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  {{- if .Values.namespace }}
  namespace: {{ .Values.namespace }}
  {{- end }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector:
    app: {{ .Values.name }}
  ports:
    - port: {{ .Values.service.port }}
      {{- if .Values.service.targetPort }}
      targetPort: {{ .Values.service.targetPort }}
      {{- end }}
{{- end }}
